sudo: required
dist: trusty
group: deprecated-2017Q4
language: node_js
node_js:
  - "8.11.1"
install: npm install
before_script:
  - npm install socket.io
script:
  - node server.js
after_failure: npm install && grunt
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
 


