sudo: required
dist: trusty
group: deprecated-2017Q4
language: node_js
node_js:
  - "8.11.1"
install: npm install
before_script:
  - npm install socket.io
  - npm install grunt-cli@0.1.13 -g
  - npm install grunt@0.4.5
  - grunt
after_failure: npm install && grunt
matrix:
  fast_finish: true
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
 


